remote_theme: pages-themes/slate@v0.2.0
lsi: false
safe: true
source: /
highlighter: rouge
incremental: false
gist:
  noscript: false
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
